### ISSUE TITLE
Can't open color schemes list

### ISSUE THREAD

**Issue by mPastuszko** [jugyo/SublimeColorSchemeSelector#7]
When I select command `Select Color Scheme` nothing opens and I get the following error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./ColorSchemeSelector.py", line 44, in run
Boost.Python.ArgumentError: Python argument types in
    Window.show_quick_panel(Window, list, function, int, int, function)
did not match C++ signature:
    show_quick_panel(SP<edit_window::reference>, boost::python::list, boost::python::api::object)
    show_quick_panel(SP<edit_window::reference>, boost::python::list, boost::python::api::object, unsigned int)
    show_quick_panel(SP<edit_window::reference>, boost::python::list, boost::python::api::object, unsigned int, int)
```

**Comment by jugyo** [comment]
Oh, you may use Sublime Text 2. I'll fix for it.

**Comment by jugyo** [comment]
I've fixed. Please try again.

**Comment by mPastuszko** [comment]
Works now. Thanks! One more question: when I browse through the list of available schemes the current scheme doesn't change instantly as shown in the [animation in README file](https://github-camo.global.ssl.fastly.net/a801ff0c014eff671831838e417010a1d81ef4b7/687474703a2f2f692e696d6775722e636f6d2f5a356876717a4f2e676966). I have to press enter key to actually swith the scheme. Is it normal or some kind of bug on my machine?

**Comment by jugyo** [comment]
I've improved to change the color scheme instantly when selection changed. So there may be some problem in your environment… i.e. the sublime text version or the plugin version.
